
firmware:
  stage: build
  script:
    - "./local/prepare-index-html"
    - "sed -i -e 's:__FW_VERSION__:'${CI_COMMIT_REF_NAME}':g' src/global.h"
    - "pio run"
    - "pio run -t buildfs"
    - "mkdir -p /srv/esp/${CI_COMMIT_REF_NAME}"
    - "chmod 777 /srv/esp/${CI_COMMIT_REF_NAME}"
    - "cp .pioenvs/esp07s/firmware.bin /srv/esp/${CI_COMMIT_REF_NAME}/4MB-firmware.bin"
    - "cp .pioenvs/esp07s/spiffs.bin /srv/esp/${CI_COMMIT_REF_NAME}/4MB-spiffs.bin"
    - "cp data/index.html.gz /srv/esp/${CI_COMMIT_REF_NAME}/esp.index.html.gz"
    - "ls -alF /srv/esp/${CI_COMMIT_REF_NAME}/"
  artifacts:
    paths:
    - .pioenvs/esp07s/firmware.bin
    - .pioenvs/esp07s/spiffs.bin
    - data/index.html.gz
  tags:
    - platformio

publish:
  stage: deploy
  script: create-index-html-esp
  artifacts:
    expire_in: 1 sec
  tags:
    - index-gen
