
firmware:
  stage: build
  script:
    - "pio run"
    - "pio run -t buildfs"
    - "mkdir -p /srv/esp/${CI_COMMIT_REF_NAME}"
    - "chmod 777 /srv/esp/${CI_COMMIT_REF_NAME}"
    - "cp .pioenvs/esp07/*.bin /srv/esp/${CI_COMMIT_REF_NAME}"
  artifacts:
    paths:
    - .pioenvs/esp07/firmware.bin
    - .pioenvs/esp07/spiffs.bin
  tags:
    - platformio

publish:
  stage: deploy
  script: create-index-html-esp
  artifacts:
    expire_in: 1 sec
  tags:
    - index-gen